name: Upload files

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js (if using Node.js tools)
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Upload files
        run: |
          # Assuming files are uploaded to the images directory
          UPLOAD_DIR="images"

          # Ensure the upload directory exists
          mkdir -p $UPLOAD_DIR

          # Check if the upload directory is not empty
          if [ -z "$(ls -A $UPLOAD_DIR)" ]; then
            echo "No files found in $UPLOAD_DIR"
            exit 1
          fi

          # Add, commit, and push the changes
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add $UPLOAD_DIR
          git commit -m "Upload files from ShareX to images directory"
          git push
