name: Rename and move files

on:
  push:
    branches:
      - main

jobs:
  rename-move:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Rename and move file
      run: |
        UPLOAD_DIR="images"
        TEMP_FILE="images/tempfile.png"

        if [ ! -f "$TEMP_FILE" ]; then
          echo "No temp file found to rename."
          exit 1
        fi

        # Generate a random filename
        RANDOM_NUM=$(shuf -i 100-999 -n 1)
        NEW_FILENAME="$UPLOAD_DIR/$RANDOM_NUM.png"

        # Move and rename the file
        mv "$TEMP_FILE" "$NEW_FILENAME"

        # Add, commit, and push the changes
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add "$NEW_FILENAME"
        git commit -m "Renamed and moved file to $NEW_FILENAME"
        git push
